// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rudp.proto

/*
Package rudpmsg is a generated protocol buffer package.

It is generated from these files:
	rudp.proto

It has these top-level messages:
	RudpMessage
	RudpMsgReg
	RudpMsgRegRs
	RudpMsgData
	RudpMsgAck
*/
package rudpmsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RudpMsgType int32

const (
	RudpMsgType_MSG_RUDP_DATA   RudpMsgType = 1
	RudpMsgType_MSG_RUDP_ACK    RudpMsgType = 2
	RudpMsgType_MSG_RUDP_REG    RudpMsgType = 3
	RudpMsgType_MSG_RUDP_REG_RS RudpMsgType = 4
)

var RudpMsgType_name = map[int32]string{
	1: "MSG_RUDP_DATA",
	2: "MSG_RUDP_ACK",
	3: "MSG_RUDP_REG",
	4: "MSG_RUDP_REG_RS",
}
var RudpMsgType_value = map[string]int32{
	"MSG_RUDP_DATA":   1,
	"MSG_RUDP_ACK":    2,
	"MSG_RUDP_REG":    3,
	"MSG_RUDP_REG_RS": 4,
}

func (x RudpMsgType) Enum() *RudpMsgType {
	p := new(RudpMsgType)
	*p = x
	return p
}
func (x RudpMsgType) String() string {
	return proto.EnumName(RudpMsgType_name, int32(x))
}
func (x *RudpMsgType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RudpMsgType_value, data, "RudpMsgType")
	if err != nil {
		return err
	}
	*x = RudpMsgType(value)
	return nil
}
func (RudpMsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RudpMessage struct {
	Type             *RudpMsgType `protobuf:"varint,1,req,name=type,enum=rudpmsg.RudpMsgType" json:"type,omitempty"`
	Data             []byte       `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *RudpMessage) Reset()                    { *m = RudpMessage{} }
func (m *RudpMessage) String() string            { return proto.CompactTextString(m) }
func (*RudpMessage) ProtoMessage()               {}
func (*RudpMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RudpMessage) GetType() RudpMsgType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return RudpMsgType_MSG_RUDP_DATA
}

func (m *RudpMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type RudpMsgReg struct {
	Seq              *int64 `protobuf:"varint,1,req,name=seq" json:"seq,omitempty"`
	Ssrc             *int64 `protobuf:"varint,2,req,name=ssrc" json:"ssrc,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RudpMsgReg) Reset()                    { *m = RudpMsgReg{} }
func (m *RudpMsgReg) String() string            { return proto.CompactTextString(m) }
func (*RudpMsgReg) ProtoMessage()               {}
func (*RudpMsgReg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RudpMsgReg) GetSeq() int64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *RudpMsgReg) GetSsrc() int64 {
	if m != nil && m.Ssrc != nil {
		return *m.Ssrc
	}
	return 0
}

type RudpMsgRegRs struct {
	Seq              *int64 `protobuf:"varint,1,req,name=seq" json:"seq,omitempty"`
	Ssrc             *int64 `protobuf:"varint,2,req,name=ssrc" json:"ssrc,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RudpMsgRegRs) Reset()                    { *m = RudpMsgRegRs{} }
func (m *RudpMsgRegRs) String() string            { return proto.CompactTextString(m) }
func (*RudpMsgRegRs) ProtoMessage()               {}
func (*RudpMsgRegRs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RudpMsgRegRs) GetSeq() int64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *RudpMsgRegRs) GetSsrc() int64 {
	if m != nil && m.Ssrc != nil {
		return *m.Ssrc
	}
	return 0
}

type RudpMsgData struct {
	Seq              *int64 `protobuf:"varint,1,req,name=seq" json:"seq,omitempty"`
	Ssrc             *int64 `protobuf:"varint,2,req,name=ssrc" json:"ssrc,omitempty"`
	Data             []byte `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RudpMsgData) Reset()                    { *m = RudpMsgData{} }
func (m *RudpMsgData) String() string            { return proto.CompactTextString(m) }
func (*RudpMsgData) ProtoMessage()               {}
func (*RudpMsgData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RudpMsgData) GetSeq() int64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *RudpMsgData) GetSsrc() int64 {
	if m != nil && m.Ssrc != nil {
		return *m.Ssrc
	}
	return 0
}

func (m *RudpMsgData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type RudpMsgAck struct {
	Seq              *int64 `protobuf:"varint,1,req,name=seq" json:"seq,omitempty"`
	Ssrc             *int64 `protobuf:"varint,2,req,name=ssrc" json:"ssrc,omitempty"`
	Data             []byte `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RudpMsgAck) Reset()                    { *m = RudpMsgAck{} }
func (m *RudpMsgAck) String() string            { return proto.CompactTextString(m) }
func (*RudpMsgAck) ProtoMessage()               {}
func (*RudpMsgAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RudpMsgAck) GetSeq() int64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *RudpMsgAck) GetSsrc() int64 {
	if m != nil && m.Ssrc != nil {
		return *m.Ssrc
	}
	return 0
}

func (m *RudpMsgAck) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*RudpMessage)(nil), "rudpmsg.RudpMessage")
	proto.RegisterType((*RudpMsgReg)(nil), "rudpmsg.RudpMsgReg")
	proto.RegisterType((*RudpMsgRegRs)(nil), "rudpmsg.RudpMsgRegRs")
	proto.RegisterType((*RudpMsgData)(nil), "rudpmsg.RudpMsgData")
	proto.RegisterType((*RudpMsgAck)(nil), "rudpmsg.RudpMsgAck")
	proto.RegisterEnum("rudpmsg.RudpMsgType", RudpMsgType_name, RudpMsgType_value)
}

func init() { proto.RegisterFile("rudp.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0x31, 0x6b, 0xc3, 0x30,
	0x10, 0x85, 0x89, 0x64, 0x28, 0x5c, 0xdd, 0x56, 0xbd, 0x76, 0xc8, 0x18, 0x3c, 0x99, 0x0e, 0x1e,
	0x42, 0xff, 0x80, 0xa8, 0x5b, 0x0f, 0x21, 0x50, 0x2e, 0xe9, 0xd0, 0xc9, 0x88, 0x58, 0x68, 0x28,
	0x25, 0xaa, 0x4f, 0x19, 0xf2, 0xef, 0x8b, 0x84, 0x51, 0xd3, 0x2d, 0x64, 0x7b, 0x3c, 0xde, 0x77,
	0x7c, 0x1c, 0xc0, 0x78, 0x18, 0x7c, 0xe3, 0xc7, 0x7d, 0xd8, 0xe3, 0x55, 0xcc, 0xdf, 0xec, 0xaa,
	0x15, 0x5c, 0xd3, 0x61, 0xf0, 0x6b, 0xcb, 0x6c, 0x9c, 0xc5, 0x1a, 0x8a, 0x70, 0xf4, 0x76, 0x3e,
	0x5b, 0x88, 0xfa, 0x76, 0xf9, 0xd8, 0x4c, 0xb3, 0x26, 0x6d, 0xd8, 0x6d, 0x8f, 0xde, 0x52, 0x5a,
	0x20, 0x42, 0x31, 0x98, 0x60, 0xe6, 0x62, 0x21, 0xea, 0x92, 0x52, 0xae, 0x96, 0x00, 0xd3, 0x90,
	0xac, 0x43, 0x05, 0x92, 0xed, 0x4f, 0x3a, 0x25, 0x29, 0xc6, 0xc8, 0x30, 0x8f, 0xbb, 0xc4, 0x48,
	0x4a, 0xb9, 0x7a, 0x86, 0xf2, 0x8f, 0x21, 0x3e, 0x93, 0xea, 0x26, 0x6d, 0x76, 0xad, 0x09, 0xe6,
	0x3c, 0x28, 0x2b, 0xcb, 0x13, 0xe5, 0xb7, 0xac, 0xac, 0x77, 0x5f, 0x97, 0xdf, 0x79, 0xfa, 0xcc,
	0x42, 0xf1, 0x47, 0x78, 0x0f, 0x37, 0xeb, 0x4d, 0xd7, 0xd3, 0x47, 0xfb, 0xde, 0xb7, 0x7a, 0xab,
	0xd5, 0x0c, 0x15, 0x94, 0xb9, 0xd2, 0x2f, 0x2b, 0x25, 0xfe, 0x35, 0xf4, 0xda, 0x29, 0x89, 0x0f,
	0x70, 0x77, 0xda, 0xf4, 0xb4, 0x51, 0xc5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x03, 0x02, 0x9c,
	0xe5, 0xb8, 0x01, 0x00, 0x00,
}
